version: '3.8'

services:
  slave:
    image: itytophile/hash-slave
    networks:
      - backend
    depends_on:
      - master
    command: /slave ws://master:3200
    deploy:
      mode: replicated
      replicas: 0

  master:
    image: maximecaricand/master:1.0
    ports:
      - 3100:3100
      - 3200:3200
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  dude:
    image: maximecaricand/dude:1.0
    depends_on:
      - master
    ports:
      - 3000:3000

networks:
  backend:
